### ISSUE TITLE
Change `audio` preset encoding to `m4a`

### ISSUE THREAD

**Issue by jamesmanning** [JimmyBoh/pully#2]
Not sure about this, so please feel free to close if ByDesign, but when passing a preset of 'audio', the resulting file definitely has only the audio stream, but is currently still saved as .mp4.  I'm assuming it's still a legal mp4 file even without a video stream in it, but having it still named .mp4 can cause a bit of confusion, where either saving it as .m4a or supporting a 'mp3' preset that saves it as .mp3 (since it already requires ffmpeg) might be a more user-friendly result?

VLC's 'codec' description of the file in case it's of any use:

![image](https://cloud.githubusercontent.com/assets/225626/8555964/bf62ed5a-24c1-11e5-8883-118d22ae3899.png)

Thanks for such a great program!  Can't wait for playlist support!

**Comment by JimmyBoh** [comment]
Hey @jamesmanning, thanks for the feedback! I actually do not have a particular preference as to which encoding it uses. The reason I have `audio` as `mp4` is because that's exactly what YouTube provides, so `audio` is really the raw audio from their servers. There is however a self-titled preset for `mp3` that does exactly what you want.

I'm open to changing the encoding of the audio preset, I can try `m4a` later today and will get back to you!

**Comment by JimmyBoh** [comment]
I'm in the process of updating the presets to use `videoIn`,`audioIn`,`videoOut`, and `audioOut` instead. This will give the user the ability to decide what the final encoding should be. Check out [the new presets.json](https://github.com/JimmyBoh/pully/blob/c3c20962db8210b861b60bec12cbc00bb6119213/data/presets.json) for the `mp3` example. It's not yet implemented, but it should allow us to have more control over post-download manipulation.

**Comment by JimmyBoh** [comment]
FYI this will soon be resolved after I implement the CLI feature of [Pully 2.0](https://github.com/JimmyBoh/pully/commits/2.0-upgrade)!

**Comment by JimmyBoh** [comment]
This is now closing in favor of #3 (which is also now implemented)

**Comment by JimmyBoh** [comment]
@jamesmanning If you are still interested in using `pully` the `mp3` preset should be right up your alley! Also regarding playlist support, `pully` will always be just a downloader, but [`pully-server`](https://github.com/JimmyBoh/pully-server) will watch and download new videos added to channels/playlists. I'm currently doing some smoke tests with un-committed code at the moment. It should be out by the end of the week!
