### ISSUE TITLE
Installed but does not run

### ISSUE THREAD

**Issue by PacoH** [JimmyBoh/pully#25]
This is exactly what I was looking for. I installed it no problem, but when I run it I get:

	$ pully
	env: node\r: No such file or directory

What does this mean and how to fix it?

**Comment by JimmyBoh** [comment]
Do you have the binary of ffmpeg available on your path? [fluent-ffmpeg](fluent-ffmpeg) has great instructions on how to do so.

**Comment by PacoH** [comment]
Of course I do. I installed it with `brew`.

	$ which ffmpeg
	/usr/local/bin/ffmpeg

But that is not the issue. The issue is still one that you were going to fix back in May, the DOS carriage return (`\r`) problem. I found the workaround––[osx cli issue · Issue #9 · JimmyBoh/pully](https://github.com/JimmyBoh/pully/issues/9#issuecomment-361810987), but I still think it needs to be fixed. I spent a lot of time before I found the simmple 'fix'.
