### ISSUE TITLE
Built-in `mp3` Preset

### ISSUE THREAD

**Issue by ayxos** [JimmyBoh/pully#3]
i dont know why is this happening

**Comment by JimmyBoh** [comment]
Can you show me the exact way you are using it? (paste the command with arguments)

**Comment by cybermarkus1** [comment]
var options = {
  url: '<some-really-high-def-video-url>',
  preset: 'mp3'
};

// 'mp3' has been defined inside presets.json

**Comment by JimmyBoh** [comment]
My apologies, it looks like there is a set of changes I never committed. `mp3` should not be in the presets. If you pulled from NPM and it has it, then I have not updated it there either.

Youtube videos don't have `mp3` streams available, so for now use the `audio` preset. Currently it will download an `mp4`, but I need to do some tweaking with that as well to make it an audio `mp4` (see #2 for details). I will try to get `mp3` working as well, but that might take some more time.

**Comment by cybermarkus1** [comment]
ok! thanks, if you need help here i am :)

**Comment by JimmyBoh** [comment]
FYI this will soon be resolved after I implement the CLI feature of [Pully 2.0](https://github.com/JimmyBoh/pully/commits/2.0-upgrade)!

**Comment by JimmyBoh** [comment]
Implemented in 4c0937a. Feel free to re-open if any problems arise!
