### ISSUE TITLE
Pully cannot find module m3u8stream/lib/parse-time

### ISSUE THREAD

**Issue by emdCatalyst** [JimmyBoh/pully#38]
Pully cannot find m3u8stream/lib/parse-time although i installed the latest version of pully and ytdl-core:
  "pully": "^2.7.0",
  "pully-core": "^0.9.1",
  "ytdl-core": "^2.1.7"
Any help would be appreciated :)

**Comment by jimbuck** [comment]
This appears to be a duplicate of #36, closing this in favor of continuing in that thread.

**Comment by emdCatalyst** [comment]
i mentioned the versions, the opposed original issue mentions that the issue was fixed in the version im using but does not seem to be true.
